### ISSUE TITLE
.dockerignore fails with different line endings

### ISSUE THREAD

**Issue by cameronroudebush** [devthefuture-org/dockerfile-x#1]
I am having issues with my .dockerignore file. Mine uses line endings of `crlf` (`\r\n`) because of Windows which causes failures pretty much immediately with this process. Switching to `lf` (`\n`) however works fine.

The error I receive is:
```
------
 > [internal] load build context:
------
ERROR: failed to solve: Internal: header key "exclude-patterns" contains value with non-printable ASCII characters
```

Could be related to: https://github.com/devthefuture-org/dockerfile-x/blob/master/pkg/llb/build.go#L459C58-L459C58

**Comment by devthejo** [comment]
this should be fixed now, thanks for pointing that @cameronroudebush
