### ISSUE TITLE
Regression on TARGETARG

### ISSUE THREAD

**Issue by bonitao** [devthefuture-org/dockerfile-x#14]
Minimal repro:

```
# syntax = devthefuture/dockerfile-x:v1.3.4
FROM alpine
ARG TARGETARCH
RUN echo $TARGETARCH > /root/targetarch.txt
CMD [ "cat" , "/root/targetarch.txt" ]
```

When running this container, instead of amd64, I get the empty string inserted in /root/targetarch.txt. If instead I use devthefuture/dockerfile-x:v1.3.3 (the previous version), then everything goes as expected.

**Comment by devthejo** [comment]
OK, thanks for reporting
related to:
- https://github.com/devthefuture-org/dockerfile-x/issues/10#issuecomment-2266330427
- https://github.com/devthefuture-org/dockerfile-x/issues/16 (duplicated issue)
