### ISSUE TITLE
Expose Dockerfile generation

### ISSUE THREAD

**Issue by davireis** [devthefuture-org/dockerfile-x#8]
Thanks a lot for this @devthejo .  I have been looking for a clean way of building a docker build pipeline for a while, and for the first time, I see something that works. FWIW, I used dockerfile-plus in the past, but it was just too primitive. The bake tool from buildkit allows for wiring dependencies but the syntax is inconvenient and lengthy, and it does not play well with the rest of the ecosystem (impressively, not even with docker-compose). The new include support in docker-compose does not address the build stage of individual services either.

Using dockerfile-x for the first time I was able to mirror the dependency tree of gradle/pnpm/etc in my monorepo. It was still sort of a pain because of the relative/absolute path problems, but I worked around it by splitting dockerfiles into "library" ones which use relative paths, and "application" ones which can only include "library" dockerfiles. 

This results in a very nice dev experience. Now I can use testcontainers+compose to build and run on-demand dependencies in a polyglot monorepo without depending on something like Bazel. Gee, even in integration tests I can programmatically bring up services in other languages using dependency injection.

My last need now is to properly add rebuild/hot module reload across programming languages. For that, I am using skaffold.dev, which likes to peek directly into the dockerfiles to see what to watch (https://github.com/GoogleContainerTools/skaffold/blob/bead9c88bdbc32bad7eadeba0ee684d9610ed149/pkg/skaffold/docker/dependencies.go#L131), and of course it baffles on dockerfile-x syntax. 

I see from dockerfile-x code that getting the "expanded" dockerfile is possible, and that would suffice for me. But I don't see that functionality exposed anywhere, as a library, a docker container, or whatever. Do you have plans to ship it externally?

**Comment by devthejo** [comment]
Hi @davireis,
it's exposed via the node package, you could use it like this `npx dockerfile-x .`
it's in the doc but not very explicitly: https://github.com/devthefuture-org/dockerfile-x#addressing-future-updates-to-dockerdockerfile
You can do `npx dockerfile-x --help` to get the documentation
This will generate a standard dockerfile from your dockerfile-x syntax
PS: if you appreciate this tool, think to leave a star ;-)
